### ISSUE TITLE
No matching distribution found for uff==0.2.0 

### ISSUE THREAD

**Issue by srcolinas** [Photogrammetry-Robotics-Bonn/bonnet#10]
Could not find a version that satisfies the requirement uff==0.2.0 (from -r train_py/requirements.txt (line 4)) (from versions: )
No matching distribution found for uff==0.2.0 (from -r train_py/requirements.txt (line 4))

is there something wrong with the requirements.txt file ?

**Comment by tano297** [comment]
Hi, 
Yes, I created the file automatically, and the tensorRT dependencies got picked up. 
I eliminated them now, if you want to use tensorRT you need to follow the dedicated install procedure in the NVIDIA site.

**Comment by srcolinas** [comment]
Thanks!
