### ISSUE TITLE
ROS catkin build

### ISSUE THREAD

**Issue by ytgcljj** [Photogrammetry-Robotics-Bonn/bonnet#13]
test16@test16:~/bonnet/deploy_cpp$ catkin build
-------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/kinetic
Workspace:                   /home/test16/bonnet/deploy_cpp
-------------------------------------------------------------------
Source Space:       [exists] /home/test16/bonnet/deploy_cpp/src
Log Space:          [exists] /home/test16/bonnet/deploy_cpp/logs
Build Space:        [exists] /home/test16/bonnet/deploy_cpp/build
Devel Space:        [exists] /home/test16/bonnet/deploy_cpp/devel
Install Space:      [unused] /home/test16/bonnet/deploy_cpp/install
DESTDIR:            [unused] None
-------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------
[build] Found '3' packages in 0.0 seconds.                                                                                                                            
[build] Updating package table.                                                                                                                                       
Warning: generated devel space setup files have been deleted.
Starting  >>> catkin_tools_prebuild                                                                                                                                   
Finished  <<< catkin_tools_prebuild                [ 5.2 seconds ]                                                                                                    
Starting  >>> bonnet_core                                                                                                                                             
______________________________________________________________________________________________________________________________________________________________________
Warnings   << bonnet_core:cmake /home/test16/bonnet/deploy_cpp/logs/bonnet_core/build.cmake.001.log                                                                   
Build type: Release
CMake Warning at /home/test16/bonnet/deploy_cpp/src/lib/CMakeLists.txt:43 (find_package):
  By not providing "FindTensorflowCC.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "TensorflowCC", but CMake did not find one.

  Could not find a package configuration file provided by "TensorflowCC" with
  any of the following names:

    TensorflowCCConfig.cmake
    tensorflowcc-config.cmake

  Add the installation prefix of "TensorflowCC" to CMAKE_PREFIX_PATH or set
  "TensorflowCC_DIR" to a directory containing one of the above files.  If
  "TensorflowCC" provides a separate development package or SDK, be sure it
  has been installed.

Tensorflow_cc shared library NOT FOUND
TF_AVAIL OFF

CUDA Libs: /usr/local/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
CUDA Headers: /usr/local/cuda/include
CUDA_AVAIL ON
TensorRT NOT Available
TRT_AVAIL OFF

OpenCV Libs: opencv_calib3d;opencv_core;opencv_dnn;opencv_features2d;opencv_flann;opencv_highgui;opencv_imgcodecs;opencv_imgproc;opencv_ml;opencv_objdetect;opencv_photo;opencv_shape;opencv_stitching;opencv_superres;opencv_video;opencv_videoio;opencv_videostab;opencv_viz;opencv_aruco;opencv_bgsegm;opencv_bioinspired;opencv_ccalib;opencv_cvv;opencv_datasets;opencv_dpm;opencv_face;opencv_fuzzy;opencv_hdf;opencv_img_hash;opencv_line_descriptor;opencv_optflow;opencv_phase_unwrapping;opencv_plot;opencv_reg;opencv_rgbd;opencv_saliency;opencv_stereo;opencv_structured_light;opencv_surface_matching;opencv_text;opencv_tracking;opencv_xfeatures2d;opencv_ximgproc;opencv_xobjdetect;opencv_xphoto
OpenCV Headers: /opt/ros/kinetic/include/opencv-3.3.1-dev;/opt/ros/kinetic/include/opencv-3.3.1-dev/opencv

YAML Libs: yaml-cpp
YAML Headers: /usr/lib/x86_64-linux-gnu/cmake/yaml-cpp/../../../../include
cd /home/test16/bonnet/deploy_cpp/build/bonnet_core; catkin build --get-env bonnet_core | catkin env -si  /usr/bin/cmake /home/test16/bonnet/deploy_cpp/src/lib --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/test16/bonnet/deploy_cpp/devel/.private/bonnet_core -DCMAKE_INSTALL_PREFIX=/home/test16/bonnet/deploy_cpp/install; cd -
......................................................................................................................................................................
______________________________________________________________________________________________________________________________________________________________________
Errors     << bonnet_core:make /home/test16/bonnet/deploy_cpp/logs/bonnet_core/build.make.001.log                                                                     
In file included from /home/test16/bonnet/deploy_cpp/src/lib/src/bonnet.cpp:19:0:
/home/test16/bonnet/deploy_cpp/src/lib/include/bonnet.hpp:33:2: error: #error ("At least TF OR TensorRT must be installed")
 #error("At least TF OR TensorRT must be installed")
  ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [CMakeFiles/bonnet_core.dir/src/bonnet.cpp.o] Error 1
make[2]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/bonnet_core.dir/all] Error 2
make: *** [all] Error 2
cd /home/test16/bonnet/deploy_cpp/build/bonnet_core; catkin build --get-env bonnet_core | catkin env -si  /usr/bin/make --jobserver-fds=3,4 -j; cd -
......................................................................................................................................................................
Failed     << bonnet_core:make                     [ Exited with code 2 ]                                                                                             
Failed    <<< bonnet_core                          [ 7.2 seconds ]                                                                                                    
Abandoned <<< bonnet_run                           [ Unrelated job failed ]                                                                                           
Abandoned <<< bonnet_standalone                    [ Unrelated job failed ]                                                                                           
[build] Summary: 1 of 4 packages succeeded.                                                                                                                           
[build]   Ignored:   None.                                                                                                                                            
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                              
[build]   Abandoned: 2 packages were abandoned.                                                                                                                       
[build]   Failed:    1 packages failed.                                                                                                                               
[build] Runtime: 12.5 seconds total.                                                                                                                                  
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/trollius/base_events.py", line 395, in __del__
  File "/usr/local/lib/python3.5/dist-packages/trollius/unix_events.py", line 65, in close
  File "/usr/local/lib/python3.5/dist-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.5/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

**Comment by tano297** [comment]
As it says in the log message, either tensorflow's shared library or tensorRT must be installed in order for the C++ interface to work. Please follow the [readme](https://github.com/Photogrammetry-Robotics-Bonn/bonnet/tree/master/deploy_cpp) to install one or the other
