### ISSUE TITLE
Setup instructions obsolete

### ISSUE THREAD

**Issue by lccatala** [Photogrammetry-Robotics-Bonn/bonnet#63]
While trying to set this up on a server for my bachelor's thesis, I found out some of the instructions are obsolete (like nvidia-docker being deprecated) and did not work by running the same commands with 'docker',  giving me a container that had some issues with CUDA drivers. 

I managed to get it working by installing everything manually in a conda environment, should I make a pull request updating the README?

**Comment by tano297** [comment]
I would greatly appreciate that.
